### ISSUE TITLE
Generate base.pak at compilation time

### ISSUE THREAD

**Issue by akien-mga** [goatattack/goatattack#17]
Currently the data are distributed in the source repo as `data/base.pak`. It makes it very impractical to modify them, check them out of curiosity, etc.
One has to guess that this `.pak` is actually a zip file and can be unzipped.

It would be much better (and would be a _strong_ requirement at least in Debian for packaging) to provide all data unzipped in `data/`, and create the .pak during the `make` call.
The `.pak` should then be removed from git and added to `.gitignore`.

**Comment by freanux** [comment]
Yes, this is really an ugly part of that package. I have to write a packager tool. It is like a zip tool, but with the restriction, that all files must be zipped in alphabetically order. why that? because during start up of the game, a hash (CRC64) of this pak file will be generated. a game server holds that hash of its zip too. these hashes will be compared together.

1) now, if the hashes of those base paks differ, the game should not be able to connect the game server. This is because some calculations are done on the server and some on the client. If maps differ, the game play will be messed up in due to calculation differences.

2) if, a game server holds one or more user defined paks, the game client will download them. this is done by comparing the hashes on both sides (client and server).

**Comment by akien-mga** [comment]
Wouldn't it work with a normal zip and a sha256sum? But yeah ensuring that game content isn't tampered with for a multiplayer game is always a tricky issue.

**Comment by freanux** [comment]
At the moment, I'm working at the package creator, called cargo. Cargo will be compiled too, but not installed. Before installing, cargo should create a sorted pak file, of all data files. If this works, i can check in all unpacked data files in github and drop the base.pak.

**Comment by freanux** [comment]
Okay, done. `goatattack-cargo` will be compiled as well. This tool then creates a `base.pak`. Unfortunately cross compiling will not work at the moment, because `goatattack-cargo` will be compiled for target architecture.
