### ISSUE TITLE
Missing dependency for ft2build.h

### ISSUE THREAD

**Issue by Thor77** [goatattack/goatattack#37]
It seems like there's something missing in your dependency list for linux:
`configure: error: missing header files:  ft2build.h`

**Comment by freanux** [comment]
As mentioned here (https://github.com/goatattack/goatattack#ft2buildh-missing) you've to add the include path of freetype.

**Comment by Thor77** [comment]
Oh, sorry, didn't read the whole file D:

**Comment by akien-mga** [comment]
You should parse the freetype2 CFLAGS @freanux:
```
$ pkg-config --cflags freetype2
-I/usr/include/freetype2 -I/usr/include/libpng16
```

**Comment by freanux** [comment]
Yes, if pkg-config is there. I think, it's up to you, how to pass the include files. For instance, I'm running a dedicated Goat Attack server on a Raspberry Pi, built with buildroot. There is no pkg-config in a cross compiled environment.

**Comment by akien-mga** [comment]
Well even if pkgconfig is not available in your use case, it's still the job of your autotools buildsystem to locate the necessary include paths and libraries and pass them to the compiler. Having freetype2 installed in `/usr/include/freetype2` is the default upstream configuration, and it should be supported out of the box, otherwise you'll just get duplicate bug reports like this one over and over. (People don't read READMEs :)).
